.dockerignore
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_requests.md
.github/workflows/deploy-concept-catalog-staging.yaml
apps/concept-catalog/Dockerfile
deploy/base/deployment-concept-catalog-frontend.yaml
deploy/base/kustomization.yaml
deploy/base/service-concept-catalog-frontend.yaml
deploy/demo/kustomization.yaml
deploy/prod/kustomization.yaml
deploy/staging/ingress.yaml
deploy/staging/kustomization.yaml

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/3

chore: deployment

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/ui/src/lib/search-hit/index.tsx
libs/ui/src/lib/tag/index.tsx

Replace code with new Tag component

chore: use Tag component in concept detail view

---

.github/workflows/deploy-prod&demo.yaml
deploy/demo/concept-catalog-frontend/concept-catalog-frontend-env.yaml
deploy/demo/concept-catalog-frontend/concept-catalog-frontend-ingress.yaml
deploy/demo/concept-catalog-frontend/kustomization.yaml
deploy/demo/kustomization.yaml
deploy/prod/concept-catalog-frontend/concept-catalog-frontend-env.yaml
deploy/prod/concept-catalog-frontend/concept-catalog-frontend-ingress.yaml
deploy/prod/concept-catalog-frontend/kustomization.yaml
deploy/prod/kustomization.yaml

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/111

chore: deployment prod + demo

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/types/next-auth.d.ts
libs/types/src/lib/history.ts

Fixes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/495

feat: display basic json patch operations

---

.github/workflows/deploy-prod&demo.yaml

fix: workflow 

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
apps/concept-catalog/types/next-auth.d.ts
libs/data-access/src/index.ts
libs/data-access/src/lib/organization/api/index.ts
libs/types/src/index.ts
libs/types/src/lib/organization.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/105

feat: organization catalog api

---

apps/catalog-admin/components/banner/banner.module.css
apps/catalog-admin/components/banner/banner.spec.tsx
apps/catalog-admin/components/banner/index.tsx
apps/catalog-admin/components/color-picker/color-picker.module.css
apps/catalog-admin/components/color-picker/index.tsx
apps/catalog-admin/components/image-uploader/image-uploader.module.css
apps/catalog-admin/components/image-uploader/image-uploader.spec.tsx
apps/catalog-admin/components/image-uploader/index.tsx
apps/catalog-admin/context/admin/action.ts
apps/catalog-admin/context/admin/context.tsx
apps/catalog-admin/context/admin/reducer.ts
apps/catalog-admin/context/admin/state.ts
apps/catalog-admin/pages/catalogs/[catalogId]/general/index.tsx
libs/utils/src/lib/language/nb.ts

feat: image uploader component

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_requests.md

solves https://github.com/Informasjonsforvaltning/catalog-frontend/issues/154

docs: update issue template

---

apps/concept-catalog/pages/[catalogId]/search-page.module.css
libs/ui/src/lib/page-banner/page-banner.module.css

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/156

fix(concept): banner tittle alignment

---

apps/catalog-admin/tsconfig.json
apps/concept-catalog/components/side-filter/index.tsx
apps/concept-catalog/hooks/comments.ts
apps/concept-catalog/hooks/concepts.ts
apps/concept-catalog/hooks/history.ts
apps/concept-catalog/hooks/import.ts
apps/concept-catalog/hooks/search.ts
apps/concept-catalog/pages/401.tsx
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
apps/concept-catalog/pages/api/comments/[...slug].ts
apps/concept-catalog/pages/api/concepts/[slug]/[conceptId]/index.ts
apps/concept-catalog/pages/api/concepts/[slug]/index.ts
apps/concept-catalog/pages/api/history/[...slug].ts
apps/concept-catalog/pages/api/search/index.ts
apps/concept-catalog/pages/auth/signin.tsx
apps/concept-catalog/tsconfig.json
apps/concept-catalog/types/next-auth.d.ts
libs/types/src/index.ts
libs/types/src/lib/error.ts
libs/utils/src/lib/language/nb.ts

chore: handle 401

---

apps/concept-catalog/pages/[catalogId]/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/139

fix: reset current page on search submit

---

apps/concept-catalog/pages/[catalogId]/index.tsx
apps/concept-catalog/pages/[catalogId]/search-page.module.css
libs/ui/src/index.ts
libs/ui/src/lib/chips/chips.module.css
libs/ui/src/lib/chips/chips.spec.tsx
libs/ui/src/lib/chips/index.tsx
libs/ui/src/lib/chips/removable.tsx
libs/ui/src/lib/chips/toggle.tsx
libs/utils/src/lib/language/nb.ts

closes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/484

feat: chips component

---

apps/concept-catalog/hooks/search.ts
apps/concept-catalog/pages/[catalogId]/index.tsx

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/192

fix(concept): change single to multiselect

---

apps/concept-catalog/hooks/search.ts
apps/concept-catalog/pages/[catalogId]/index.tsx

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/201

Revert "fix(concept): change single to multiselect"

---

apps/catalog-admin/pages/catalogs/[catalogId]/general/design/index.tsx
apps/concept-catalog/pages/404.tsx
apps/concept-catalog/pages/500.tsx
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
apps/concept-catalog/pages/[catalogId]/no-access.tsx
apps/concept-catalog/pages/auth/signin.tsx
apps/concept-catalog/pages/auth/signout.tsx
deploy/demo/concept-catalog-frontend/concept-catalog-frontend-env.yaml
deploy/prod/concept-catalog-frontend/concept-catalog-frontend-env.yaml
libs/ui/src/lib/breadcrumbs/index.tsx
libs/ui/src/lib/error-boundry/index.tsx

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/206

fix(breadcrumbs): add missing envs

---

apps/concept-catalog/.env.local.example
deploy/demo/catalog-admin-frontend/catalog-admin-frontend-env.yaml
deploy/prod/catalog-admin-frontend/catalog-admin-frontend-env.yaml
deploy/staging/catalog-admin-frontend/catalog-admin-frontend-env.yaml
deploy/staging/concept-catalog-frontend/concept-catalog-frontend-env.yaml
libs/ui/src/lib/error-boundry/index.tsx

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/206
staging-deployment-filen manglet base uri

fix: staging env

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
libs/utils/src/lib/auth/token/index.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/197
Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/739

feat: check write permissions

---

libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/205

chore: change no access text

---

apps/concept-catalog/hooks/concepts.ts
apps/concept-catalog/pages/api/concepts/[slug]/index.ts

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/235

fix(concept): remove prefilled placeholder on concept creation

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/types/src/lib/concept.ts
libs/ui/src/lib/search-hit/__snapshots__/search-hit-empty.spec.tsx.snap
libs/ui/src/lib/search-hit/__snapshots__/search-hit.spec.tsx.snap
libs/ui/src/lib/search-hit/index.tsx
libs/ui/src/lib/search-hit/search-hit.module.css
libs/utils/src/lib/language/nb.ts
libs/utils/src/lib/validation/uuid.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/232

fix: edit/delete unpublished revision

---

README.md
apps/concept-catalog/components/side-filter/checkbox-group-filter.tsx
apps/concept-catalog/components/side-filter/index.tsx
apps/concept-catalog/context/search/action.ts
apps/concept-catalog/context/search/reducer.ts
apps/concept-catalog/context/search/state.ts
apps/concept-catalog/hooks/user-list.ts
apps/concept-catalog/pages/api/user-list/[...slug].ts
libs/data-access/src/lib/user-list/api/index.ts
libs/types/src/index.ts
libs/types/src/lib/mapper.ts

resolves https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/541
closes https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/506

feat(concept): select assigned user

---

apps/catalog-admin/middleware.ts
apps/catalog-admin/pages/catalogs/[catalogId]/no-access.tsx

feat: show no access page for users that are not orgAdmin

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/types/src/lib/concept.ts
libs/utils/src/index.ts
libs/utils/src/lib/text/text.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/250

fix: object.keys default to emtpy object

---

apps/catalog-admin/pages/catalogs/[catalogId]/concepts/internal-fields/index.tsx

fix: bug in internal fields

---

apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx

feat: search functionality for code lists

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/types/src/lib/concept.ts
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/276

feat: display abbreviatedLabel

---

apps/catalog-admin/components/banner/index.tsx
apps/catalog-admin/components/code-list-editor/index.tsx
apps/catalog-admin/pages/_app.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/concepts/editable-fields/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/concepts/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/concepts/internal-fields/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/general/design/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/general/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/general/users/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/index.tsx
libs/ui/src/lib/card/card.module.css
libs/ui/src/lib/card/index.tsx
libs/utils/src/lib/language/nb.ts

fix: first code does not get id

---

apps/concept-catalog/context/search/action.ts
apps/concept-catalog/context/search/reducer.ts
apps/concept-catalog/context/search/state.ts
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
libs/types/src/lib/concept.ts
libs/ui/src/lib/search-hit-container/index.tsx
libs/ui/src/lib/search-hit/index.tsx
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/70

feat(concept): label (merkelapp)

---

apps/concept-catalog/components/search-filter/checkbox-group-filter.tsx
apps/concept-catalog/components/search-filter/checkbox-tree-filter/checkbox-tree.module.css
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/change-requests/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
libs/ui/src/lib/pagination/index.tsx
libs/ui/src/lib/search-hit-container/index.tsx
libs/ui/src/lib/search-hit/index.tsx
libs/ui/src/lib/search-hit/search-hit.module.css
libs/ui/src/lib/tag/index.tsx
libs/ui/src/lib/tag/tag.module.css

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/294

feat (concept): use fds tag component

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/[catalogId]/index.tsx
libs/utils/src/index.ts
libs/utils/src/lib/reference-data/index.ts

Ok å legge metoden inn i libs/utils?
Tenker at vi slenger inn alle endringene vi ville gjøre med statuslista der, dvs endring av nåværende labels og sortering.

feat: add rejected status

---

apps/concept-catalog/pages/[catalogId]/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/310

fix (concept): match subject on parent

---

apps/concept-catalog/pages/[catalogId]/index.tsx

fix: show concept status label in filter chips

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/296

chore: change  definition translation

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/759

feat (concept): add contactinformation to detailpage

---

apps/concept-catalog/components/related-concepts/associative-relations/index.tsx
apps/concept-catalog/components/related-concepts/generic-relations/index.tsx
apps/concept-catalog/components/related-concepts/index.tsx
apps/concept-catalog/components/related-concepts/is-replaced-by/index.tsx
apps/concept-catalog/components/related-concepts/partitive-relations/index.tsx
apps/concept-catalog/components/related-concepts/see-also/index.tsx
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/data-access/src/lib/concept/api/index.ts
libs/data-access/src/lib/search-fulltext/api/index.ts
libs/types/src/lib/concept.ts
libs/types/src/lib/enums.ts
libs/ui/src/index.ts
libs/ui/src/lib/key-value-list-item/index.tsx
libs/ui/src/lib/key-value-list-item/key-value-list-item.module.css
libs/ui/src/lib/key-value-list/index.tsx
libs/ui/src/lib/key-value-list/key-value-list.module.css
libs/utils/src/lib/date/format.ts
libs/utils/src/lib/functions/index.ts
libs/utils/src/lib/language/nb.ts

resolves https://github.com/Informasjonsforvaltning/catalog-frontend/issues/308

feat(concept): add related concepts

---

apps/concept-catalog/pages/[catalogId]/index.tsx

fix (concept): do not include empty value for internal field filter

---

apps/concept-catalog/pages/[catalogId]/change-requests/[changeRequestId]/edit.tsx
apps/concept-catalog/pages/api/change-requests/[catalogId]/index.ts
libs/data-access/src/lib/change-requests/api/index.ts
libs/types/src/lib/change-request.ts

Feat/ts/change request/341/api call get change request

---

apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/804

fix (concept): check empty values

---

apps/concept-catalog/hooks/concepts.ts
apps/concept-catalog/pages/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/api/concepts/[slug]/[conceptId]/publish.ts
libs/data-access/src/lib/concept/api/index.ts
libs/ui/src/lib/detail-heading/detail-heading.module.css
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/concept-catalog/issues/291

feat (concept): publish concept

---

apps/concept-catalog/hooks/change-requests.ts
apps/concept-catalog/pages/[catalogId]/change-requests/[changeRequestId]/_change-request-form.tsx
apps/concept-catalog/pages/[catalogId]/change-requests/[changeRequestId]/edit.tsx
apps/concept-catalog/pages/[catalogId]/change-requests/new.tsx
apps/concept-catalog/pages/api/change-requests/[...slug].ts
libs/data-access/src/lib/change-requests/api/index.ts
libs/utils/src/lib/language/nb.ts

Feat/change request/344/update existing change request

---

apps/catalog-admin/components/code-list-editor/index.tsx
apps/catalog-admin/components/codes-editor/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
libs/ui/src/index.ts
libs/ui/src/lib/use-warn-if-unsaved-changes/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/813

feat (catalog-admin): detect unsaved changes

---

apps/concept-catalog/components/definition/definition.module.css
apps/concept-catalog/components/definition/index.tsx
apps/concept-catalog/components/related-concepts/generic-relations/index.tsx
apps/concept-catalog/components/related-concepts/partitive-relations/index.tsx
apps/concept-catalog/pages/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/357

feat (concept): minor layout changes

---

apps/concept-catalog/pages/[catalogId]/change-requests/[changeRequestId]/_change-request-form.tsx
apps/concept-catalog/pages/[catalogId]/change-requests/[changeRequestId]/edit.tsx
apps/concept-catalog/pages/[catalogId]/change-requests/index.tsx
apps/concept-catalog/pages/[catalogId]/change-requests/new.tsx
libs/utils/src/lib/language/nb.ts

Feat/ts/change request/fix and move breadcrumbs

---

apps/concept-catalog/pages/[catalogId]/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/379

feat (concept): feature toggle for change requests

---

apps/concept-catalog/components/search-filter/index.tsx
apps/concept-catalog/pages/[catalogId]/[conceptId]/index.tsx
apps/concept-catalog/pages/api/concepts/[slug]/[conceptId]/index.ts
apps/concept-catalog/pages/api/concepts/[slug]/[conceptId]/publish.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/381
Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/384

fix (concept): hide if filter options are empty

---

apps/catalog-admin/components/code-list-editor/index.tsx
apps/catalog-admin/components/codes-editor/index.tsx
apps/catalog-admin/pages/catalogs/[catalogId]/concepts/code-lists/index.tsx
libs/ui/src/lib/card/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/387

fix (catalog-admin): code-list blocking

---

libs/ui/src/lib/header/header.module.css
libs/ui/src/lib/header/index.tsx

related to https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/817

feat: update header design

---

apps/service-catalog/app/catalogs/[catalogId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/edit/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/new/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/edit/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/new/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/page.tsx
apps/service-catalog/app/page.tsx
libs/types/src/lib/service.ts

Feat/ha/setup routing service catalog, closes #369

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/app/[catalogId]/search-page-client.tsx
apps/concept-catalog/app/api/history/[...slug]/route.ts
apps/concept-catalog/hooks/history.ts
libs/data-access/src/lib/catalog-history/api/index.ts
libs/ui/src/lib/pagination/index.tsx
libs/ui/src/lib/search-hit-container/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/421

feat (concept): add concept history paging

---

apps/concept-catalog/app/[catalogId]/search-page-client.tsx
libs/ui/src/lib/pagination/index.tsx
libs/ui/src/lib/search-hit-container/index.tsx

resolves https://github.com/Informasjonsforvaltning/catalog-frontend/issues/415

fix(concept): paginate via url

---

apps/service-catalog/app/catalogs/[catalogId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services-page.module.css
apps/service-catalog/app/page.tsx
libs/utils/src/lib/language/nb.ts

feat: add navigation cards service catalog

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/public-service-details-page.module.css
apps/service-catalog/app/catalogs/[catalogId]/public-services/page.tsx
apps/service-catalog/components/buttons/index.tsx
libs/types/src/lib/service.ts
libs/ui/src/index.ts
libs/ui/src/lib/details-page-layout/details-page.module.css
libs/ui/src/lib/details-page-layout/index.tsx
libs/utils/src/lib/language/nb.ts

chore: make details page as a component and public-service details page

---

apps/catalog-admin/components/codes-editor/index.tsx
apps/catalog-admin/components/internal-field-editor/index.tsx
apps/concept-catalog/components/search-filter/checkbox-tree-filter/checkbox-tree.module.css
apps/concept-catalog/components/search-filter/checkbox-tree-filter/index.tsx
package.json
yarn.lock

fix: design bugs introduced when upgrading design system

---

apps/service-catalog/app/actions/public-services/actions.ts
apps/service-catalog/app/actions/services/actions.ts
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/page.tsx
apps/service-catalog/components/basic-form-info-card-items/basic-form-info-card-items.module.css
apps/service-catalog/components/basic-form-info-card-items/index.tsx
apps/service-catalog/components/basic-service-form/index.tsx
apps/service-catalog/components/basic-service-form/service-form.module.css
apps/service-catalog/components/basic-service-form/service-template.tsx
apps/service-catalog/components/buttons/buttons.module.css
apps/service-catalog/components/buttons/index.tsx
libs/data-access/src/lib/services/api/index.tsx
libs/types/src/lib/service.ts
libs/ui/src/index.ts
libs/ui/src/lib/divider-line/divider-line.module.css
libs/ui/src/lib/divider-line/divider-line.spec.tsx
libs/ui/src/lib/divider-line/index.tsx
libs/utils/src/index.ts
libs/utils/src/lib/language/nb.ts
libs/utils/src/lib/object-manipulation/index.ts

Feat/ha/add contactPoint and produces to service

---

apps/service-catalog/app/actions/public-services/actions.ts
apps/service-catalog/app/actions/services/actions.ts
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/edit/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/public-service-details-page.module.css
apps/service-catalog/app/catalogs/[catalogId]/public-services/new/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/edit/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/new/page.tsx
apps/service-catalog/components/basic-service-form/index.tsx
apps/service-catalog/components/basic-service-form/service-template.tsx
libs/data-access/src/index.ts
libs/data-access/src/lib/statuses/api/index.tsx
libs/types/src/lib/service.ts
libs/ui/src/lib/tag/index.tsx
libs/ui/src/lib/tag/tag.module.css

feat: add statuses to services

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/change-request-edit-page-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/change-requests-page.module.css
apps/concept-catalog/app/[catalogId]/change-requests/new/new-concept-suggestion-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/page.tsx
apps/concept-catalog/components/banner/index.tsx
apps/concept-catalog/components/change-request-form/change-request-form.tsx
libs/data-access/src/lib/change-requests/api/index.ts
libs/types/src/lib/change-request.ts
libs/types/src/lib/user.ts

* edit ChangeRequest types
* stringify request body in API
* make a separate banner component
resolves #454

refactor(concept:changeRequest): edit page and new concept suggestion page

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/change-requests-page.module.css
libs/ui/src/lib/layout/global.css
libs/utils/src/lib/language/nb.ts

feat(concept:changeRequest): show information about form

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/change-request-edit-page-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/new-concept-suggestion-client.tsx
apps/concept-catalog/components/change-request-form/change-request-form.tsx
libs/ui/src/lib/form-field-card/field-header/field-header.module.css
libs/ui/src/lib/form-field-card/field-header/index.tsx
libs/ui/src/lib/form-field-card/index.tsx

feat(concept:changeRequest): colorize edited fields

---

apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/edit/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/new/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/edit/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/new/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/page.tsx
libs/utils/src/lib/language/nb.ts

feat: add breadcrumbs to service catalog

---

apps/concept-catalog/app/page.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/514

fix: opt in dynamic rendering

---

apps/catalog-admin/app/catalogs/[catalogId]/concepts/code-lists/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/concepts/editable-fields/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/concepts/internal-fields/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/concepts/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/general/design/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/general/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/general/users/page.tsx
apps/catalog-admin/app/catalogs/[catalogId]/page.tsx
apps/catalog-admin/app/page.tsx
apps/catalog-admin/utils/auth.ts

fix (catalog-admin): not use redirect in promise

---

apps/service-catalog/app/actions/public-services/actions.ts
apps/service-catalog/app/actions/services/actions.ts
apps/service-catalog/components/basic-service-form/index.tsx
apps/service-catalog/components/publish-switch/index.tsx
libs/utils/src/lib/language/nb.ts

feat: add error handling service

---

apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/public-service-details-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/service-details-page-client.tsx
apps/service-catalog/components/basic-form-info-card-items/index.tsx
apps/service-catalog/components/basic-service-form/index.tsx
apps/service-catalog/components/basic-service-form/service-template.tsx
apps/service-catalog/middleware.ts
libs/utils/src/lib/language/nb.ts

feat: add support for multiple languages service form

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/463

fix (concept): not allow publish for user with read rights

---

apps/catalog-admin/app/notfound/page.tsx
apps/catalog-admin/utils/auth.ts
apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
apps/concept-catalog/app/[catalogId]/[conceptId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/[conceptId]/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/page.tsx
apps/concept-catalog/app/[catalogId]/new/page.tsx
apps/concept-catalog/app/[catalogId]/page.tsx
apps/concept-catalog/app/notfound/page.tsx
apps/concept-catalog/components/catalog-layout/index.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/page.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/page.tsx
apps/service-catalog/app/notfound/page.tsx
apps/service-catalog/middleware.ts
libs/utils/src/lib/auth/route-guard/index.tsx

fix (concept): prevent all tabs from rerendering when using paging

---

apps/concept-catalog/app/[catalogId]/search-page-client.tsx
apps/concept-catalog/components/search-filter/checkbox-tree-filter/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/809

fix (concept): subject filter

---

apps/concept-catalog/app/[catalogId]/search-page-client.tsx

fix (concept): smooth scroll to top on page change

---

apps/concept-catalog/app/[catalogId]/search-page-client.tsx
apps/concept-catalog/components/related-concepts/generic-relations/index.tsx
apps/concept-catalog/components/related-concepts/partitive-relations/index.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/481

fix (concept): display relation type

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/change-request-edit-page-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/change-request-or-new-client.tsx
libs/utils/src/index.ts
libs/utils/src/lib/concept/index.tsx

fix(concept:changeRequest): remove sources if egendefinert

---

apps/concept-catalog/app/[catalogId]/change-requests/page.tsx
apps/concept-catalog/app/[catalogId]/search-page-client.tsx
libs/ui/src/lib/select/style.module.css

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/556

fix: set max select width

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/change-requests-page-client.tsx

fix(concept:changeRequest): handle no title in list view

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/change-requests-page-client.tsx

feat(concept:changeRequest): update text for change request info

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/page.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/change-request-or-new-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/page.tsx
apps/concept-catalog/components/buttons/index.tsx
apps/concept-catalog/components/change-request-form/change-request-form.tsx
apps/concept-catalog/components/source-section/index.tsx
apps/concept-catalog/components/source-section/relation-to-source/index.tsx
apps/concept-catalog/components/source-section/source-for-definition/index.tsx
libs/ui/src/lib/custom-error/index.tsx
libs/ui/src/lib/search-hit-container/index.tsx

Fix/ts/change request/dont show diff on new suggestion

---

apps/concept-catalog/components/concept-search-hits/index.tsx
libs/ui/src/lib/tag/change-request-status/ChangeRequestStatus.tsx
libs/ui/src/lib/tag/concept-status/ConceptStatus.tsx
libs/ui/src/lib/tag/service-status/ServiceStatus.tsx

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/581

fix: add forwardRef to status tags

---

apps/concept-catalog/components/related-concepts/generic-relations/index.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/861

fix(concept): show correct generic relation

---

apps/concept-catalog/components/related-concepts/associative-relations/index.tsx
apps/concept-catalog/components/related-concepts/generic-relations/index.tsx
apps/concept-catalog/components/related-concepts/index.tsx
apps/concept-catalog/components/related-concepts/is-replaced-by/index.tsx
apps/concept-catalog/components/related-concepts/partitive-relations/index.tsx
apps/concept-catalog/components/related-concepts/see-also/index.tsx
libs/utils/src/lib/date/format.ts
libs/utils/src/lib/language/nb.ts

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/589

fix(concept): partitive relation translation

---

apps/catalog-admin/app/catalogs/[catalogId]/concepts/code-lists/code-list-page-client.tsx
apps/catalog-admin/components/code-list-editor/index.tsx
apps/catalog-admin/components/codes-editor/codes-editor.module.css
apps/catalog-admin/components/codes-editor/index.tsx
libs/types/src/lib/code-list.ts
libs/utils/src/lib/code-list/index.ts

fix: use uuid as id for codes

---

apps/concept-catalog/app/[catalogId]/search-page-client.tsx

fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/605

fix(concept): filter subject tag text visibility

---

apps/concept-catalog/components/related-concepts/see-also/index.tsx

fix: remove hasExpired and willBeValid from details page concept catalog

---

apps/catalog-admin/app/catalogs/[catalogId]/concepts/editable-fields/editable-fields-client.tsx
apps/catalog-admin/components/internal-field-editor/index.tsx
libs/utils/src/lib/language/nb.ts

closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/872
closes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/826

fix: not able to save editable field when only one codelist

---

apps/concept-catalog/components/search-filter/checkbox-tree-filter/index.tsx
apps/concept-catalog/components/search-filter/index.tsx

fix: not possible to select empty in dropdown filtert concept catalog

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/change-requests-page-client.tsx
apps/concept-catalog/app/[catalogId]/search-page-client.tsx
apps/concept-catalog/components/buttons/index.tsx
apps/concept-catalog/components/search-filter/checkbox-tree-filter/index.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/public-service-details-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/public-service-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/service-details-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/service-page-client.tsx
apps/service-catalog/components/basic-service-form/index.tsx
libs/ui/src/lib/button/index.tsx
libs/ui/src/lib/button/link.tsx
libs/ui/src/lib/button/upload.tsx
package.json
yarn.lock

chore: update design system

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page.module.css
apps/concept-catalog/app/api/search/route.ts
libs/ui/src/lib/search-hit/__snapshots__/search-hit-empty.spec.tsx.snap
libs/ui/src/lib/search-hit/__snapshots__/search-hit.spec.tsx.snap
libs/ui/src/lib/search-hit/index.tsx
libs/ui/src/lib/search-hit/search-hit-empty.spec.tsx
libs/ui/src/lib/search-hit/search-hit.module.css
libs/ui/src/lib/search-hit/search-hit.spec.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/620

fix: status tag with long title

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
libs/types/src/lib/comment.ts

fix: comment user can be null

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
libs/utils/src/lib/language/nb.ts

closes [#775](https://github.com/Informasjonsforvaltning/behov/issues/775)

fix: update text sist oppdatert skos v2

---

apps/catalog-admin/components/user-editor/index.tsx
apps/concept-catalog/app/[catalogId]/[conceptId]/page.tsx
apps/concept-catalog/components/related-concepts/index.tsx
libs/data-access/src/lib/code-list/api/index.ts
libs/data-access/src/lib/concept/api/index.ts
libs/utils/src/lib/concept/index.tsx
libs/utils/src/lib/regex/regex.ts

fix: internal published concept relations not pointing to correct version

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/public-service-details-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/public-services/[serviceId]/public-service-details-page.module.css
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/service-details-page-client.tsx
apps/service-catalog/app/catalogs/[catalogId]/services/[serviceId]/service-details-page.module.css
libs/ui/src/lib/concept-subject/index.tsx
libs/ui/src/lib/details-page-layout/details-page.module.css
libs/ui/src/lib/details-page-layout/index.tsx
libs/utils/src/lib/concept/index.tsx

chore: refactor details page layout component

---

libs/utils/src/lib/code-list/index.ts

closes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/536

fix: code not shwoing when removing parent catalog admin codelists

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page-client.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page.module.css
libs/utils/src/lib/language/nb.ts

part of https://github.com/Informasjonsforvaltning/catalog-frontend/issues/715

feat: add searchbar to datasets

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page-client.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page.module.css
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/new/page.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/series/new/page.tsx
deploy/demo/dataset-catalog-frontend/dataset-catalog-frontend-env.yaml
deploy/prod/dataset-catalog-frontend/dataset-catalog-frontend-env.yaml
deploy/staging/dataset-catalog-frontend/dataset-catalog-frontend-env.yaml
libs/utils/src/lib/language/nb.ts

closes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/715

Feat: Add button to go to "add datasets" page

---

apps/catalog-portal/Dockerfile
apps/catalog-portal/app/actions/actions.ts
apps/catalog-portal/app/auth/signin/page.tsx
apps/catalog-portal/app/auth/signout/page.tsx
apps/catalog-portal/app/catalogs/page.tsx
apps/catalog-portal/app/page.tsx
apps/catalog-portal/specs/index.spec.tsx
codegen.yml
deploy/demo/catalog-portal-frontend/catalog-portal-frontend-env.yaml
deploy/prod/catalog-portal-frontend/catalog-portal-frontend-env.yaml
deploy/staging/catalog-portal-frontend/catalog-portal-frontend-env.yaml
libs/data-access/src/index.ts
libs/data-access/src/lib/records-of-processing-activities/api/index.tsx
libs/data-access/src/lib/strapi/generated/graphql.ts
libs/data-access/src/lib/strapi/graphql/service-message.graphql
libs/data-access/src/lib/strapi/service-messages/index.tsx
libs/ui/src/index.ts
libs/ui/src/lib/service-messages/index.tsx
libs/ui/src/lib/service-messages/service-messages.module.css
libs/ui/src/lib/service-messages/service-messages.spec.tsx
libs/utils/src/lib/language/nb.ts
package.json
yarn.lock

part of https://github.com/Informasjonsforvaltning/catalog-frontend/issues/759

feat: add service messages to catalog-portal

---

apps/catalog-portal/app/catalogs/page.tsx
libs/utils/src/lib/auth/token/index.ts
libs/utils/src/lib/functions/index.ts
libs/utils/src/lib/language/nb.ts

closes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/759

chore: refactor catalog-portal

---

apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/validation-schema.tsx
libs/utils/src/lib/language/dataset.form.nb.ts
libs/utils/src/lib/object-manipulation/index.ts

part of https://github.com/Informasjonsforvaltning/catalog-frontend/issues/804

add validation to dataset form dataset-catalog

---

apps/catalog-admin/app/layout.tsx
apps/catalog-portal/app/layout.tsx
apps/concept-catalog/app/layout.tsx
apps/data-service-catalog/app/layout.tsx
apps/dataset-catalog/app/layout.tsx
apps/service-catalog/app/layout.tsx
libs/ui/src/lib/layout/global.css

related to https://github.com/Informasjonsforvaltning/architecture-decision-log/issues/4

feat: use os specific font

---

apps/dataset-catalog/app/actions/actions.ts
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page-client.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/page.tsx
apps/dataset-catalog/app/context/themes/index.tsx
apps/dataset-catalog/app/layout.tsx
apps/dataset-catalog/components/dataset-form/dataset-form-access-rights.section.tsx
apps/dataset-catalog/components/dataset-form/dataset-form-tema-section.tsx
apps/dataset-catalog/components/dataset-form/dataset-form.module.css
apps/dataset-catalog/components/dataset-form/dataset-initial-values.tsx
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/validation-schema.tsx
libs/data-access/src/index.ts
libs/data-access/src/lib/themes/api/index.tsx
libs/types/src/index.ts
libs/types/src/lib/dataset.ts
libs/types/src/lib/theme.ts
libs/utils/src/lib/language/dataset.form.nb.ts

related to https://github.com/Informasjonsforvaltning/catalog-frontend/issues/801
OBS! Henting av reference-data blir gjort om i neste PR

feat: add tema section to dataset form

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/data-services-page-client.tsx
libs/utils/src/lib/language/nb.ts

feat: search data services

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/data-services-page-client.tsx
apps/data-service-catalog/components/status-filter/index.tsx
apps/data-service-catalog/components/status-filter/status-filter.module.css

feat: filter data services on status

---

apps/dataset-catalog/components/dataset-form/components/dataset-form-qualified-attributions-section.tsx
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/utils/dataset-initial-values.tsx
apps/dataset-catalog/hooks/useEnhetsregister.ts
libs/data-access/src/index.ts
libs/data-access/src/lib/enhetsregisteret/index.tsx
libs/types/src/index.ts
libs/types/src/lib/dataset.ts
libs/types/src/lib/enhet.ts
libs/utils/src/lib/language/dataset.form.nb.ts
libs/utils/src/lib/regex/regex.ts

feat: add qualifiedAttributions to dataset form

---

apps/data-service-catalog/app/actions/actions.ts
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/page.tsx
apps/data-service-catalog/components/data-service-form/components/data-service-form-title-section.tsx
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/components/search-hit-table/index.tsx
apps/data-service-catalog/next-env.d.ts
libs/data-access/src/lib/data-service/api/index.ts
libs/utils/src/lib/language/data.service.form.nb.ts
libs/utils/src/lib/language/localization.ts

feat: initial data service form with title section

---

apps/dataset-catalog/components/dataset-form/components/dataset-form-example-data-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-geography-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-information-model-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-qualified-attributions-section.tsx
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/utils/dataset-initial-values.tsx
apps/dataset-catalog/hooks/useReferenceDataSearch.ts
libs/data-access/src/index.ts
libs/data-access/src/lib/reference-data/api/index.ts
libs/data-access/src/lib/reference-data/generated/graphql.ts
libs/types/src/lib/dataset.ts
libs/types/src/lib/reference-data.ts
libs/ui/src/index.ts
libs/ui/src/lib/formik-search-combobox/formik-search-combobox.spec.tsx
libs/ui/src/lib/formik-search-combobox/index.tsx
libs/utils/src/lib/functions/index.ts
libs/utils/src/lib/language/dataset.form.nb.ts

feat: add example data to dataset form

---

.github/workflows/deploy-prod&demo.yaml
.github/workflows/deploy-staging.yaml
apps/concept-catalog/components/concept-search-hits/index.tsx
deploy/base/catalog-admin-frontend/kustomization.yaml
deploy/base/catalog-portal-frontend/kustomization.yaml
deploy/base/concept-catalog-frontend/kustomization.yaml
deploy/base/data-service-catalog-frontend/kustomization.yaml
deploy/base/dataset-catalog-frontend/kustomization.yaml
deploy/base/service-catalog-frontend/kustomization.yaml
libs/types/src/lib/concept.ts
libs/utils/src/lib/language/nb.ts

chore: replace revision link in concept search hit with last published

---

apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/change-request-edit-page-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/change-request-or-new-client.tsx
apps/concept-catalog/app/[catalogId]/change-requests/new/page.tsx

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1022

fix: use originalId when creating change request for concept

---

apps/concept-catalog/app/[catalogId]/[conceptId]/concept-page-client.tsx

feat: show merkelapp as chip in concept details page

---

apps/dataset-catalog/components/dataset-form/components/dataset-form-access-rights-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-concept-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-content-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-example-data-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-geography-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-information-model-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-provenance-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-qualified-attributions-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-theme-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-type-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-from-title-section.tsx
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/utils/dataset-initial-values.tsx
apps/dataset-catalog/components/fieldset-with-delete/fieldset-with-delete.module.scss
apps/dataset-catalog/components/fieldset-with-delete/index.tsx
libs/ui/src/index.ts
libs/ui/src/lib/button/add.tsx
libs/ui/src/lib/button/button.module.css
libs/ui/src/lib/button/delete.tsx
libs/utils/src/lib/language/dataset.form.nb.ts

relates to #801 
Steg 1, skal rydde, refakturere og gjøre om på design

feat: add design to dataset-form

---

apps/dataset-catalog/app/actions/actions.ts
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/edit/page.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/new/page.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-access-rights-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-concept-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-content-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-provenance-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-from-distribution/dataset-form-distribution-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-from-distribution/distribution-details.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-from-distribution/distribution-modal.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-from-distribution/distributions.module.css
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/utils/dataset-initial-values.tsx
apps/dataset-catalog/components/dataset-form/utils/validation-schema.tsx
apps/dataset-catalog/hooks/useSearchService.ts
libs/types/src/lib/data-service.ts
libs/types/src/lib/dataset.ts
libs/types/src/lib/reference-data.ts
libs/utils/src/lib/language/dataset.form.nb.ts
libs/utils/src/lib/language/nb.ts

feat: add distribution to dataset form

---

apps/catalog-portal-e2e/src/page-object-model/loginPage.ts
apps/catalog-portal-e2e/src/tests/admin/catalogPortalPage.spec.ts
apps/concept-catalog/components/related-concepts/index.tsx
apps/service-catalog-e2e/src/page-object-model/loginPage.ts
libs/utils/src/lib/concept/index.tsx

Cannot open https://begrepskatalog.fellesdatakatalog.digdir.no/974760673/62da6996-cf72-438f-be46-d72841bd0b05
Cause: TypeError: null is not an object (evaluating 'e.match')

fix: handle possible undefined/null value

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/edit/page.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/new/page.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-geography-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-form-information-model-section.tsx
apps/dataset-catalog/components/dataset-form/components/dataset-from-distribution/distribution-modal.tsx
apps/dataset-catalog/components/dataset-form/dataset-form.module.css
apps/dataset-catalog/components/dataset-form/index.tsx
libs/ui/src/index.ts
libs/ui/src/lib/sticky-footer-bar/index.tsx
libs/utils/src/lib/language/dataset.form.nb.ts
libs/utils/src/lib/language/nb.ts

feat: add sticky footer dataset form

---

apps/catalog-portal/.env.serve.e2e
apps/catalog-portal/app/actions/actions.ts
deploy/demo/data-service-catalog-frontend/data-service-catalog-frontend-env.yaml
deploy/prod/data-service-catalog-frontend/data-service-catalog-frontend-env.yaml
deploy/staging/data-service-catalog-frontend/data-service-catalog-frontend-env.yaml
libs/data-access/src/lib/data-service/api/index.ts

chore: use new backend in data-service-catalog

---

apps/catalog-portal-e2e/src/page-object-model/catalogPortalPage.ts
apps/data-service-catalog/app/actions/actions.ts
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/data-services-page-client.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/page.tsx
apps/data-service-catalog/components/data-service-form/components/data-service-form-endpoint-section.tsx
apps/data-service-catalog/components/data-service-form/components/data-service-form-title-section.tsx
apps/data-service-catalog/components/data-service-form/data-service-form.module.css
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/components/data-service-form/utils/data-service-initial-values.tsx
apps/data-service-catalog/components/search-hit-table/index.tsx
libs/data-access/src/lib/data-service/api/index.ts
libs/types/src/lib/data-service.ts
libs/utils/src/lib/language/data.service.form.nb.ts
libs/utils/src/lib/language/nb.ts

feat: page & form for creating new data services

---

apps/data-service-catalog/components/data-service-form/components/contact-point-section.tsx
apps/data-service-catalog/components/data-service-form/data-service-form.module.css
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/components/data-service-form/utils/data-service-initial-values.tsx
libs/types/src/lib/data-service.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: data service form contact section

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/app/layout.tsx
apps/data-service-catalog/components/data-service-form/components/format-section.tsx
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/hooks/useReferenceDataSearch.ts
libs/types/src/lib/data-service.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: data service form format section

---

apps/data-service-catalog/components/data-service-form/components/format-section.tsx
apps/data-service-catalog/components/data-service-form/components/pages-section.tsx
apps/data-service-catalog/components/data-service-form/components/pages.module.css
apps/data-service-catalog/components/data-service-form/index.tsx
libs/types/src/lib/data-service.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: api form landing page & documentation

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/components/data-service-form/components/dataset-section.tsx
apps/data-service-catalog/components/data-service-form/data-service-form.module.css
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/hooks/useSearchService.ts
libs/types/src/lib/data-service.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: data service form dataset section

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/components/data-service-form/components/access-section.tsx
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/hooks/useReferenceDataSearch.ts
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/edit/page.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/page.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/new/page.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-modal.tsx
libs/types/src/lib/data-service.ts
libs/types/src/lib/reference-data.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: data service form access section

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/components/data-service-form/components/documentation-section.tsx
apps/data-service-catalog/components/data-service-form/components/endpoint-section.tsx
apps/data-service-catalog/components/data-service-form/components/status-section.tsx
apps/data-service-catalog/components/data-service-form/index.tsx
libs/data-access/src/lib/reference-data/api/index.ts
libs/types/src/lib/reference-data.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: add status field to data service form

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/components/data-service-form/components/status-section.tsx
apps/data-service-catalog/components/data-service-form/index.tsx
libs/data-access/src/lib/reference-data/api/index.ts
libs/types/src/lib/data-service.ts
libs/types/src/lib/reference-data.ts
libs/utils/src/lib/language/data.service.form.nb.ts

feat: add availability to data service form

---

apps/data-service-catalog/components/data-service-form/components/contact-point-section.tsx
apps/data-service-catalog/components/data-service-form/components/costs-table.tsx
apps/data-service-catalog/components/data-service-form/index.tsx
apps/data-service-catalog/components/data-service-form/utils/validation-schema.tsx
libs/utils/src/lib/language/nb.ts

feat: data service form validation

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page.module.css
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/data-services-page-client.tsx
apps/data-service-catalog/components/status-tag/index.tsx

feat: title, status and buttons in API details page

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/components/details-page-columns/details-columns.module.css
apps/data-service-catalog/components/details-page-columns/details-page-left-column.tsx

feat: add description and keywords to API details page

---

apps/dataset-catalog/components/dataset-form/components/about-section.tsx
apps/dataset-catalog/components/dataset-form/components/access-rights.tsx/access-rights-uri-table.tsx
apps/dataset-catalog/components/dataset-form/components/access-rights.tsx/dataset-form-access-rights-section.tsx
apps/dataset-catalog/components/dataset-form/components/concept-section.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/hidden-detail-fields.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/recommended-detail-fields.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/temporal-modal.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-modal.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distributions.module.css
apps/dataset-catalog/components/dataset-form/components/information-model-section.tsx
apps/dataset-catalog/components/dataset-form/components/qualified-attributions-section.tsx
apps/dataset-catalog/components/dataset-form/components/relations-section/references-table.tsx
apps/dataset-catalog/components/dataset-form/components/relations-section/relations-section.tsx
apps/dataset-catalog/components/dataset-form/components/uri-with-label-field-set-table.tsx
apps/dataset-catalog/components/dataset-form/dataset-form.module.css
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/hooks/useReferenceDataSearch.ts
libs/ui/src/lib/search-hit/search-hit.module.css
libs/ui/src/lib/search-hits-page-layout/search-hits-page-layout.module.css
libs/utils/src/lib/language/dataset.form.nb.ts

- Fjerne ariaLabel og id fra TitleWithHelptext
- Legge til border for modal 
- Sette fieldset til størrelse s for å få lik font-size på overskrifter
- Fikse import av graphQL
- venstrestille searchContainer (ref nytt design)
- Wordbreak for beskrivelse i search hit cards
relates to #923

fix: small fixes dataset form

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/components/details-page-columns/details-columns.module.css
apps/data-service-catalog/components/details-page-columns/details-page-right-column.tsx
libs/utils/src/lib/language/data.service.form.nb.ts

feat: add ID, contact and modified date to API details page

---

apps/data-service-catalog/app/actions/actions.ts
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/page.tsx
apps/data-service-catalog/components/details-page-columns/details-columns.module.css
apps/data-service-catalog/components/details-page-columns/details-page-right-column.tsx
apps/data-service-catalog/components/publish-switch/index.tsx
libs/data-access/src/lib/data-service/api/index.ts
libs/types/src/lib/data-service.ts

feat: publish API from details page

---

apps/data-service-catalog/components/details-page-columns/components/cost-list.tsx
apps/data-service-catalog/components/details-page-columns/details-page-left-column.tsx

feat: add costs to API details page

---

apps/data-service-catalog/components/data-service-form/components/about-section.tsx
apps/data-service-catalog/components/data-service-form/components/access-section.tsx
apps/data-service-catalog/components/data-service-form/components/contact-point-section.tsx
apps/data-service-catalog/components/data-service-form/components/costs-table.tsx
apps/data-service-catalog/components/data-service-form/components/dataset-section.tsx
apps/data-service-catalog/components/data-service-form/components/documentation-section.tsx
apps/data-service-catalog/components/data-service-form/components/endpoint-section.tsx
apps/data-service-catalog/components/data-service-form/components/format-section.tsx
apps/data-service-catalog/components/data-service-form/components/status-section.tsx
libs/ui/src/lib/sticky-footer-bar/sticky-footer-bar.module.css

part of https://github.com/Informasjonsforvaltning/catalog-frontend/issues/1031

fix: less spacing in data-service form

---

apps/data-service-catalog/components/data-service-form/components/costs-table.tsx
apps/data-service-catalog/components/data-service-form/components/documentation-section.tsx
apps/data-service-catalog/components/data-service-form/components/endpoint-section.tsx
libs/ui/src/lib/formik-fast-field-with-ref/index.tsx
libs/ui/src/lib/formik-language-fieldset/index.tsx

chore: focus on new fields when added to API-form

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/components/data-service-form/components/contact-point-section.tsx
apps/data-service-catalog/components/data-service-form/components/costs-table.tsx
apps/data-service-catalog/components/data-service-form/utils/validation-schema.tsx
apps/data-service-catalog/components/details-page-columns/components/cost-list.tsx
apps/data-service-catalog/components/details-page-columns/details-page-left-column.tsx
apps/data-service-catalog/components/details-page-columns/details-page-right-column.tsx
libs/types/src/lib/data-service.ts
libs/ui/src/index.ts
libs/ui/src/lib/formik-optional-fields-fieldset/formik-optional-fields-fieldset.module.scss
libs/ui/src/lib/formik-optional-fields-fieldset/index.tsx
libs/utils/src/lib/language/data.service.form.nb.ts

feat: use generic optional fields component in API contact section

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/page.tsx
apps/data-service-catalog/components/details-page-columns/details-page-right-column.tsx
libs/ui/src/lib/info-card/info-card-item.tsx

feat: disable API-publish when invalid

---

apps/concept-catalog/components/concept-form/validation-schema.tsx

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/1052

chore: if not required skip version validation

---

apps/dataset-catalog/components/dataset-form/components/about-section.tsx
apps/dataset-catalog/components/dataset-form/components/access-rights.tsx/access-rights-section.tsx
apps/dataset-catalog/components/dataset-form/components/concept-section.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/details.module.css
apps/dataset-catalog/components/dataset-form/components/details-section/hidden-detail-fields.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/recommended-detail-fields.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/temporal-modal.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-modal.tsx
apps/dataset-catalog/components/dataset-form/components/information-model-section.tsx
apps/dataset-catalog/components/dataset-form/components/qualified-attributions-section.tsx
apps/dataset-catalog/components/dataset-form/components/theme-section.tsx
apps/dataset-catalog/components/dataset-form/dataset-form-theme-section.tsx
apps/dataset-catalog/components/dataset-form/dataset-form.module.css
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/utils/validation-schema.tsx
libs/ui/src/lib/formik-reference-data-combobox/index.tsx
libs/utils/src/lib/date/format.ts
libs/utils/src/lib/language/dataset.form.nb.ts

fix: smaller width and validation calendars dataset form

---

apps/dataset-catalog/components/dataset-form/components/contact-point-section.tsx
libs/ui/src/lib/formik-optional-fields-fieldset/index.tsx

fix: update contact point design dataset form

---

apps/dataset-catalog/components/dataset-form/components/about-section.tsx
apps/dataset-catalog/components/dataset-form/components/access-rights.tsx/access-rights-uri-table.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/details-section.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/hidden-detail-fields.tsx
apps/dataset-catalog/components/dataset-form/components/details-section/temporal-modal.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-section.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distributions.module.scss
apps/dataset-catalog/components/dataset-form/components/qualified-attributions-section.tsx
apps/dataset-catalog/components/dataset-form/components/relations-section/references-table.tsx
apps/dataset-catalog/components/dataset-form/components/relations-section/relations-section.tsx
apps/dataset-catalog/components/dataset-form/components/toggle-field-button.tsx
apps/dataset-catalog/components/dataset-form/components/uri-with-label-field-set-table.tsx
apps/dataset-catalog/components/dataset-form/dataset-form.module.css
apps/dataset-catalog/components/details-page-columns/components/access-rights-details.tsx
apps/dataset-catalog/components/details-page-columns/components/temporal-details.tsx
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx
apps/dataset-catalog/components/uri-with-label-table/index.tsx

fix: make tables full width and fixed dataset catalog

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page-client.tsx
libs/ui/src/lib/search-hit-container/index.tsx

feat: add pagination to dataset-catalog

---

apps/dataset-catalog/app/actions/actions.ts
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx
apps/dataset-catalog/components/details-page-columns/details-page-right-column.tsx
libs/utils/src/lib/language/dataset.form.nb.ts
libs/utils/src/lib/text/capitalize.ts

fix: small fixes dataset-catalog details page

---

apps/dataset-catalog/hooks/useSearchService.ts
tsconfig.base.json

resolve https://github.com/Informasjonsforvaltning/catalog-frontend/issues/1121

fix: set pagination data when searching for dataset relations by uri

---

libs/utils/src/lib/language/nb.ts

Resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1143

fix: Add creation date label #1143

---

apps/concept-catalog/app/catalogs/[catalogId]/change-requests/[changeRequestId]/accept-concept-form-client.tsx
apps/concept-catalog/app/catalogs/[catalogId]/change-requests/[changeRequestId]/edit/edit-concept-form-client.tsx
apps/concept-catalog/app/catalogs/[catalogId]/change-requests/new/new-concept-form-client.tsx
apps/concept-catalog/app/catalogs/[catalogId]/change-requests/new/page.tsx
apps/concept-catalog/app/catalogs/[catalogId]/concepts/[conceptId]/edit/edit-page.client.tsx
apps/concept-catalog/app/catalogs/[catalogId]/concepts/new/new-page.client.tsx
apps/concept-catalog/components/concept-form/index.tsx
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/catalog-frontend/issues/1110

feat: goto concept button if original concept is defined

---

apps/concept-catalog/utils/json-patch.ts

Bør merge denne samtidig som denne: https://github.com/Informasjonsforvaltning/concept-catalog/pull/438

fix: rm omitBy isNull from concept compare function

---

apps/dataset-catalog/components/dataset-form/components/about-section.tsx
apps/dataset-catalog/components/dataset-form/dataset-form.module.css
apps/dataset-catalog/components/dataset-form/index.tsx
apps/dataset-catalog/components/dataset-form/utils/validation-schema.tsx
libs/utils/src/lib/language/dataset.form.nb.ts

resolve #1126 
resolve #1131 
bunnmenyen blir seende ut som dette:

feat: add ignoreRequired in dataset form

---

libs/ui/src/lib/formik-language-fieldset/index.tsx
libs/ui/src/lib/formik-multivalue-textfield/index.tsx

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1144

fix: remove allowDeleteWhenReadOnly

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/dataset-details-page-client.tsx
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx

feat: support markdown for descriptions in dataset-catalog

---

apps/dataset-catalog/components/details-page-columns/components/access-rights-details.tsx
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx

fix: add language input to getTranslateText where missing in dataset details

---

apps/dataset-catalog/components/details-page-columns/components/temporal-details.tsx
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx
apps/dataset-catalog/components/details-page-columns/details-page-right-column.tsx
libs/utils/src/lib/date/format.ts

use format dd.MM.yyyy for all dates

---

apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
libs/ui/src/index.ts

#1129 
Jeg muliggjørde klikkbarhet bare fir tilgangstjeneste. Jeg er usikker hvis vi skal gjøre det for alle.

fix: make tags in service access clickable

---

apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-modal.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-section.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distributions.module.scss
apps/dataset-catalog/components/dataset-form/utils/dataset-initial-values.tsx
libs/types/src/lib/dataset.ts
libs/utils/src/lib/language/dataset.form.nb.ts

dataset distribution section bugs

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/dataset-details-page-client.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/edit/edit-page-client.tsx
apps/dataset-catalog/app/catalogs/[catalogId]/datasets/datasets-page-client.tsx

feat: disable dataset series

---

apps/dataset-catalog/components/dataset-form/index.tsx

fix: use datasetTemplate when setting initial values

---

libs/ui/__mocks__/empty-mock.ts
libs/ui/jest.config.ts
libs/ui/src/lib/search-hit/__snapshots__/search-hit.spec.tsx.snap
libs/ui/src/lib/search-hit/index.tsx

fix: support markdown in SearchHit component

---

libs/utils/src/lib/language/dataset.form.nb.ts

fix: change help text and landing page text

---

apps/catalog-portal/app/catalogs/[[...catalogId]]/page.tsx
libs/utils/src/lib/language/nb.ts

Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/930

feat: add alert if no organizations are available

---

apps/dataset-catalog/components/dataset-form/utils/dataset-initial-values.tsx
libs/types/src/lib/dataset.ts

chore: add uri fields to dataset type

---

apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/data-service-details-page-client.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/edit/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/[dataServiceId]/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/data-services-page-client.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/data-services-page.module.css
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/new/page.tsx
apps/data-service-catalog/app/catalogs/[catalogId]/data-services/page.tsx

liten oppdatering av datatjenestesidene for å få de til å ligne mer på sidene til de andre katalogene

refactor: update data-service pages

---

apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-section.tsx
apps/dataset-catalog/components/details-page-columns/components/distribution-details.tsx

fixes #1205 
Finnes eget issue for feilen i fdk-frontend: https://github.com/Informasjonsforvaltning/fdk-frontend/issues/478

fix: show all urls for dataset distributions

---

apps/dataset-catalog/components/dataset-form/components/details-section/minimized-detail-fields.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
apps/dataset-catalog/components/details-page-columns/components/access-rights-details.tsx
apps/dataset-catalog/components/details-page-columns/components/distribution-details.tsx
apps/dataset-catalog/components/details-page-columns/details-columns.module.css
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx
apps/dataset-catalog/components/details-page-columns/details-page-right-column.tsx
apps/dataset-catalog/components/uri-with-label-table/index.tsx

resolve #1211 
resolve #1217 
resolve #1223
resolve #1224
fixes #1218

fix: clickable links in dataset details page

---

apps/dataset-catalog/components/dataset-form/components/details-section/temporal-modal.tsx
apps/dataset-catalog/components/details-page-columns/components/temporal-details.tsx

fix: use arrayHelpers for temporal list in dataset form

---

apps/dataset-catalog/components/details-page-columns/components/access-rights-details.tsx
apps/dataset-catalog/components/details-page-columns/details-page-left-column.tsx

fix: always show dataset legal basis

---

apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-details.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-modal.tsx
apps/dataset-catalog/components/dataset-form/components/distribution-section/distribution-section.tsx
apps/dataset-catalog/components/dataset-form/components/relations-section/references-table.tsx

refactor: reduce searches

---

apps/catalog-portal-e2e/src/tests/admin/catalogPortalPage.spec.ts
apps/catalog-portal/.env.serve.e2e
apps/catalog-portal/app/catalogs/[[...catalogId]]/page.tsx
deploy/demo/catalog-portal-frontend/catalog-portal-frontend-env.yaml
deploy/prod/catalog-portal-frontend/catalog-portal-frontend-env.yaml
deploy/staging/catalog-portal-frontend/catalog-portal-frontend-env.yaml

feat: route to new dataset pages from catalog-portal

---

apps/dataset-catalog/app/catalogs/[catalogId]/datasets/[datasetId]/dataset-details-page-client.tsx
apps/dataset-catalog/components/dataset-form/components/contact-point-section.tsx
apps/dataset-catalog/components/dataset-form/utils/validation-schema.tsx
apps/dataset-catalog/components/details-page-columns/details-page-right-column.tsx
libs/types/src/lib/dataset.ts
libs/utils/src/lib/language/dataset.form.nb.ts

feat: add name to dataset contactPoints

---

apps/concept-catalog/components/concept-form/validation-schema.tsx

improve: validate url if required or value is not empty

---

package.json
yarn.lock

improve: audit fix
